# ========================
# General project settings
# ========================
project_name: "NucleiSegmentation"

# =====================
# Model configuration
# =====================
model:
  name: "UNET"
  params:
    in_channels: 1
    out_channels: 1
    features: [64, 128, 256, 512]

# =====================
# Training configuration
# =====================
training:
  epochs: 100
  batch_size: 16
  learning_rate: 0.001
  loss_function: "DiceLoss"
  image_dir: "data/processed/train_images"   # Directory with training images
  mask_dir: "data/processed/train_masks"     # Directory with corresponding masks
  val_split_ratio: 0.2                        # Percentage of data used for validation
  patch_size: [256, 256]
  patch_stride: [128, 128]
  num_workers: 0
  device: "mps"                               # Options: "cuda", "mps", or "cpu"

# =================================
# Experiment tracking and logging
# =================================
logging:
  exp_name: "experiment_1"                   # Used to organize checkpoints and results
  log_dir: "runs/"
  checkpoint_dir: "checkpoints/"             # Base checkpoint directory (exp_name will be appended)
  results_dir: "results/"                    # Base results directory (exp_name will be appended)
  save_interval: 10                          # Save model every N epochs (besides best model)

# =====================
# Inference configuration
# =====================
inference:
  test_image_dir: "data/raw/stage1_test"     # Path to raw test images
  output_mask_dir: "results/predictions"     # Directory where predicted masks will be saved
  flask_output_mask_dir: "data/processed/flask_predictions"
  display_limit: 10                          # How many predictions to display (0 = none, -1 = all)
